"""Cambia el tamaño de la columna imagen

Revision ID: 800f14ee21a3
Revises: 
Create Date: 2023-12-04 00:42:33.480597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '800f14ee21a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.String(length=5000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('producto', schema=None) as batch_op:
        batch_op.alter_column('imagen',
               existing_type=sa.String(length=5000),
               type_=mysql.VARCHAR(length=1000),
               existing_nullable=True)

    # ### end Alembic commands ###
